trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- script: |
    cd terraform
    terraform init
    terraform validate
    terraform plan
    terraform apply
  displayName: 'Terraform init, validate, plan and apply'