trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: latest

- task: AzureCLI@2
  inputs:
    azureSubscription: 'MyConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform validate
      terraform plan
      terraform apply -auto-approve
  displayName: 'Terraform init, validate, plan and apply'