resource_group_name = "Smugj_Project_RG"
location            = "East US"
acr_name            = "smugjacr2026"
vm_name             = "smugj-flask-vm"
admin_username      = "azureuser"
admin_password      = "SecurePassword123!@#"
subscription_id     = "YOUR_AZURE_SUBSCRIPTION_ID"